services:
  bot:
    container_name: bot
    image: bot:latest
    build: .
    environment:
      - TZ=Europe/Moscow
      - secret=secret
    depends_on:
      - bot_database

    restart: always
  bot_database:
    container_name: bot_database
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - TZ=Europe/Moscow
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
